<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Clicker</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
    <Prefer32Bit>True</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <ApplicationConfig Remove="Clicker.exe.config" />
    <ApplicationConfig Include="Clicker.exe.config" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Gma.System.MouseKeyHook">
      <HintPath>..\Gma.System.MouseKeyHook.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>